stages: [ .pre, lint, build, test, deploy ]

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - when: never

include:
  - local: .gitlab/ci/common.yml
  - local: backend/tasker/.gitlab-ci.yml