stages: [ .pre, lint, build, test, merge_ok, deploy ]

workflow:
  rules:
    # Запускаем для merge request
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Запускаем для git тегов (релизы)
    - if: $CI_COMMIT_TAG
    - when: never

include:
  - local: .gitlab/ci/common.yml
  - local: backend/tasker/.gitlab-ci.yml

merge_request_checks:
  stage: merge_ok
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - echo "Merge request pipeline checks"