"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetGmailTokensRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_EMAIL_FIELD_NUMBER: builtins.int
    user_email: builtins.str
    def __init__(
        self,
        *,
        user_email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_email", b"user_email"]) -> None: ...

Global___GetGmailTokensRequest: typing_extensions.TypeAlias = GetGmailTokensRequest
