# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x0c\x63ommon.proto\"+\n\x15GetGmailTokensRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t2Q\n\x0b\x41uthService\x12\x42\n\x0eGetGmailTokens\x12\x1b.auth.GetGmailTokensRequest\x1a\x11.auth.GmailTokens\"\x00\x42\x1a\xaa\x02\x17Personage.Auth.Api.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\027Personage.Auth.Api.Grpc'
  _globals['_GETGMAILTOKENSREQUEST']._serialized_start=34
  _globals['_GETGMAILTOKENSREQUEST']._serialized_end=77
  _globals['_AUTHSERVICE']._serialized_start=79
  _globals['_AUTHSERVICE']._serialized_end=160
# @@protoc_insertion_point(module_scope)
