"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ServiceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ServiceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ServiceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ServiceType_Unknown: _ServiceType.ValueType  # 0
    ServiceType_Gmail: _ServiceType.ValueType  # 1
    ServiceType_Telegram: _ServiceType.ValueType  # 2

class ServiceType(_ServiceType, metaclass=_ServiceTypeEnumTypeWrapper): ...

ServiceType_Unknown: ServiceType.ValueType  # 0
ServiceType_Gmail: ServiceType.ValueType  # 1
ServiceType_Telegram: ServiceType.ValueType  # 2
Global___ServiceType: typing_extensions.TypeAlias = ServiceType

@typing.final
class GmailTokens(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    GMAIL_EMAIL_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    refresh_token: builtins.str
    gmail_email: builtins.str
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
        expires_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        gmail_email: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["expires_at", b"expires_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "expires_at", b"expires_at", "gmail_email", b"gmail_email", "refresh_token", b"refresh_token"]) -> None: ...

Global___GmailTokens: typing_extensions.TypeAlias = GmailTokens

@typing.final
class TelegramSession(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_STRING_FIELD_NUMBER: builtins.int
    session_string: builtins.str
    def __init__(
        self,
        *,
        session_string: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_string", b"session_string"]) -> None: ...

Global___TelegramSession: typing_extensions.TypeAlias = TelegramSession
