# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import state_tracking_pb2 as state__tracking__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in state_tracking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StateTrackingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsersForProcessing = channel.unary_unary(
                '/auth.StateTrackingService/GetUsersForProcessing',
                request_serializer=state__tracking__pb2.GetUsersForProcessingRequest.SerializeToString,
                response_deserializer=state__tracking__pb2.GetUsersForProcessingResponse.FromString,
                _registered_method=True)
        self.MarkUsersAsProcessed = channel.unary_unary(
                '/auth.StateTrackingService/MarkUsersAsProcessed',
                request_serializer=state__tracking__pb2.MarkUsersAsProcessedRequest.SerializeToString,
                response_deserializer=state__tracking__pb2.MarkUsersAsProcessedResponse.FromString,
                _registered_method=True)


class StateTrackingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsersForProcessing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkUsersAsProcessed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StateTrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsersForProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersForProcessing,
                    request_deserializer=state__tracking__pb2.GetUsersForProcessingRequest.FromString,
                    response_serializer=state__tracking__pb2.GetUsersForProcessingResponse.SerializeToString,
            ),
            'MarkUsersAsProcessed': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkUsersAsProcessed,
                    request_deserializer=state__tracking__pb2.MarkUsersAsProcessedRequest.FromString,
                    response_serializer=state__tracking__pb2.MarkUsersAsProcessedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.StateTrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.StateTrackingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StateTrackingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsersForProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.StateTrackingService/GetUsersForProcessing',
            state__tracking__pb2.GetUsersForProcessingRequest.SerializeToString,
            state__tracking__pb2.GetUsersForProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkUsersAsProcessed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.StateTrackingService/MarkUsersAsProcessed',
            state__tracking__pb2.MarkUsersAsProcessedRequest.SerializeToString,
            state__tracking__pb2.MarkUsersAsProcessedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
