"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import common_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetUsersForProcessingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BATCH_SIZE_FIELD_NUMBER: builtins.int
    MIN_SECONDS_SINCE_LAST_PROCESS_FIELD_NUMBER: builtins.int
    SERVICE_TYPE_FIELD_NUMBER: builtins.int
    batch_size: builtins.int
    min_seconds_since_last_process: builtins.int
    service_type: common_pb2.ServiceType.ValueType
    def __init__(
        self,
        *,
        batch_size: builtins.int = ...,
        min_seconds_since_last_process: builtins.int = ...,
        service_type: common_pb2.ServiceType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["batch_size", b"batch_size", "min_seconds_since_last_process", b"min_seconds_since_last_process", "service_type", b"service_type"]) -> None: ...

Global___GetUsersForProcessingRequest: typing_extensions.TypeAlias = GetUsersForProcessingRequest

@typing.final
class GetUsersForProcessingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___UserForProcessing]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[Global___UserForProcessing] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["users", b"users"]) -> None: ...

Global___GetUsersForProcessingResponse: typing_extensions.TypeAlias = GetUsersForProcessingResponse

@typing.final
class UserForProcessing(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    LAST_PROCESSED_AT_FIELD_NUMBER: builtins.int
    CREDENTIALS_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    @property
    def last_processed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def credentials(self) -> Global___ProcessingCredentials: ...
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        last_processed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        credentials: Global___ProcessingCredentials | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credentials", b"credentials", "last_processed_at", b"last_processed_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials", "last_processed_at", b"last_processed_at", "user_id", b"user_id"]) -> None: ...

Global___UserForProcessing: typing_extensions.TypeAlias = UserForProcessing

@typing.final
class ProcessingCredentials(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GMAIL_TOKENS_FIELD_NUMBER: builtins.int
    TELEGRAM_SESSION_FIELD_NUMBER: builtins.int
    @property
    def gmail_tokens(self) -> common_pb2.GmailTokens: ...
    @property
    def telegram_session(self) -> common_pb2.TelegramSession: ...
    def __init__(
        self,
        *,
        gmail_tokens: common_pb2.GmailTokens | None = ...,
        telegram_session: common_pb2.TelegramSession | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["credentials", b"credentials", "gmail_tokens", b"gmail_tokens", "telegram_session", b"telegram_session"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["credentials", b"credentials", "gmail_tokens", b"gmail_tokens", "telegram_session", b"telegram_session"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["credentials", b"credentials"]) -> typing.Literal["gmail_tokens", "telegram_session"] | None: ...

Global___ProcessingCredentials: typing_extensions.TypeAlias = ProcessingCredentials

@typing.final
class MarkUsersAsProcessedRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    SERVICE_TYPE_FIELD_NUMBER: builtins.int
    service_type: common_pb2.ServiceType.ValueType
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ProcessedUser]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[Global___ProcessedUser] | None = ...,
        service_type: common_pb2.ServiceType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["service_type", b"service_type", "users", b"users"]) -> None: ...

Global___MarkUsersAsProcessedRequest: typing_extensions.TypeAlias = MarkUsersAsProcessedRequest

@typing.final
class ProcessedUser(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    PROCESSED_AT_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    @property
    def processed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        processed_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["processed_at", b"processed_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["processed_at", b"processed_at", "user_id", b"user_id"]) -> None: ...

Global___ProcessedUser: typing_extensions.TypeAlias = ProcessedUser

@typing.final
class MarkUsersAsProcessedResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___MarkUsersAsProcessedResponse: typing_extensions.TypeAlias = MarkUsersAsProcessedResponse
