"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StoreSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    SESSION_STRING_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    session_string: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        session_string: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_string", b"session_string", "user_id", b"user_id"]) -> None: ...

Global___StoreSessionRequest: typing_extensions.TypeAlias = StoreSessionRequest

@typing.final
class StoreSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StoreSessionResponse: typing_extensions.TypeAlias = StoreSessionResponse

@typing.final
class GetSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["user_id", b"user_id"]) -> None: ...

Global___GetSessionRequest: typing_extensions.TypeAlias = GetSessionRequest

@typing.final
class GetSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_STRING_FIELD_NUMBER: builtins.int
    session_string: builtins.str
    def __init__(
        self,
        *,
        session_string: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_string", b"session_string"]) -> None: ...

Global___GetSessionResponse: typing_extensions.TypeAlias = GetSessionResponse
