# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telegram_pb2 as telegram__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in telegram_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelegramServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreSession = channel.unary_unary(
                '/auth.TelegramService/StoreSession',
                request_serializer=telegram__pb2.StoreSessionRequest.SerializeToString,
                response_deserializer=telegram__pb2.StoreSessionResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/auth.TelegramService/GetSession',
                request_serializer=telegram__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=telegram__pb2.GetSessionResponse.FromString,
                _registered_method=True)


class TelegramServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelegramServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreSession,
                    request_deserializer=telegram__pb2.StoreSessionRequest.FromString,
                    response_serializer=telegram__pb2.StoreSessionResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=telegram__pb2.GetSessionRequest.FromString,
                    response_serializer=telegram__pb2.GetSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.TelegramService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.TelegramService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelegramService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.TelegramService/StoreSession',
            telegram__pb2.StoreSessionRequest.SerializeToString,
            telegram__pb2.StoreSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.TelegramService/GetSession',
            telegram__pb2.GetSessionRequest.SerializeToString,
            telegram__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
