# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telegram.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'telegram.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etelegram.proto\x12\x04\x61uth\">\n\x13StoreSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0esession_string\x18\x02 \x01(\t\"\x16\n\x14StoreSessionResponse\"$\n\x11GetSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\",\n\x12GetSessionResponse\x12\x16\n\x0esession_string\x18\x01 \x01(\t2\x99\x01\n\x0fTelegramService\x12\x45\n\x0cStoreSession\x12\x19.auth.StoreSessionRequest\x1a\x1a.auth.StoreSessionResponse\x12?\n\nGetSession\x12\x17.auth.GetSessionRequest\x1a\x18.auth.GetSessionResponseB#\xaa\x02 Personage.Auth.Api.Grpc.Telegramb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telegram_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002 Personage.Auth.Api.Grpc.Telegram'
  _globals['_STORESESSIONREQUEST']._serialized_start=24
  _globals['_STORESESSIONREQUEST']._serialized_end=86
  _globals['_STORESESSIONRESPONSE']._serialized_start=88
  _globals['_STORESESSIONRESPONSE']._serialized_end=110
  _globals['_GETSESSIONREQUEST']._serialized_start=112
  _globals['_GETSESSIONREQUEST']._serialized_end=148
  _globals['_GETSESSIONRESPONSE']._serialized_start=150
  _globals['_GETSESSIONRESPONSE']._serialized_end=194
  _globals['_TELEGRAMSERVICE']._serialized_start=197
  _globals['_TELEGRAMSERVICE']._serialized_end=350
# @@protoc_insertion_point(module_scope)
