# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telegram_chats.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telegram_chats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14telegram_chats.proto\x12\x04\x61uth\"-\n\x13GetUserChatsRequest\x12\x16\n\x0esession_string\x18\x01 \x01(\t\"h\n\x14GetUserChatsResponse\x12.\n\x05\x63hats\x18\x01 \x03(\x0b\x32\x1f.auth.GetUserChatsResponse.Chat\x1a \n\x04\x43hat\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t2]\n\x14TelegramChatsService\x12\x45\n\x0cGetUserChats\x12\x19.auth.GetUserChatsRequest\x1a\x1a.auth.GetUserChatsResponseB(\xaa\x02%Personage.Auth.Api.Grpc.TelegramChatsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telegram_chats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002%Personage.Auth.Api.Grpc.TelegramChats'
  _globals['_GETUSERCHATSREQUEST']._serialized_start=30
  _globals['_GETUSERCHATSREQUEST']._serialized_end=75
  _globals['_GETUSERCHATSRESPONSE']._serialized_start=77
  _globals['_GETUSERCHATSRESPONSE']._serialized_end=181
  _globals['_GETUSERCHATSRESPONSE_CHAT']._serialized_start=149
  _globals['_GETUSERCHATSRESPONSE_CHAT']._serialized_end=181
  _globals['_TELEGRAMCHATSSERVICE']._serialized_start=183
  _globals['_TELEGRAMCHATSSERVICE']._serialized_end=276
# @@protoc_insertion_point(module_scope)
