services:
  tasker-eval:
    depends_on:
      - db
    build:
      context: .
      dockerfile: go.Dockerfile
      args:
        service: tasker
    environment:
      APP_ENV: eval
      CONFIGS_PATH: /app/configs
      EVAL_QUEUE_URL: ${EVAL_QUEUE_URL}
    env_file:
      - ../secrets.env
    ports:
      - "8091:8080"
      - "9091:9090"
