services:
  tasker:
    build:
      context: .
      dockerfile: go.Dockerfile
      args:
        service: tasker
    environment:
      APP_ENV: dev
      CONFIGS_PATH: /app/configs
    env_file:
      - secrets.env
    ports:
      - "8080:8080"
      - "9090:9090"