services:
  auth:
    image: cr.yandex/crp77qhpsda1m6ian417/auth:dev
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    env_file:
      - ../secrets.env
    ports:
      - "8082:5254"
      - "50051:50051"

  tasker:
    depends_on:
      - db
    build:
      context: .
      dockerfile: go.Dockerfile
      args:
        service: tasker
    environment:
      APP_ENV: dev
      CONFIGS_PATH: /app/configs
    env_file:
      - ../secrets.env
    ports:
      - "8080:8080"
      - "9090:9090"

  notificator:
    depends_on:
      - db
    build:
      context: .
      dockerfile: go.Dockerfile
      args:
        service: notificator
    environment:
      APP_ENV: dev
      CONFIGS_PATH: /app/configs
    env_file:
      - ../secrets.env
    ports:
      - "8080:8080"
      - "9090:9090"

  db:
    image: pgvector/pgvector:pg18-trixie
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  pgdata: