"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StoreSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    SESSION_STRING_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    session_string: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        session_string: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_string", b"session_string", "user_id", b"user_id"]) -> None: ...

Global___StoreSessionRequest: typing_extensions.TypeAlias = StoreSessionRequest

@typing.final
class StoreSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___StoreSessionResponse: typing_extensions.TypeAlias = StoreSessionResponse

@typing.final
class GetSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    INCLUDE_ENCRYPTED_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    include_encrypted: builtins.bool
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        include_encrypted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["include_encrypted", b"include_encrypted", "user_id", b"user_id"]) -> None: ...

Global___GetSessionRequest: typing_extensions.TypeAlias = GetSessionRequest

@typing.final
class GetSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    SESSION_STRING_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    EXISTS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    session_string: builtins.str
    user_id: builtins.str
    exists: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        session_string: builtins.str = ...,
        user_id: builtins.str = ...,
        exists: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["exists", b"exists", "message", b"message", "session_string", b"session_string", "success", b"success", "user_id", b"user_id"]) -> None: ...

Global___GetSessionResponse: typing_extensions.TypeAlias = GetSessionResponse

@typing.final
class InvalidateSessionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    REASON_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    reason: builtins.str
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        reason: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["reason", b"reason", "user_id", b"user_id"]) -> None: ...

Global___InvalidateSessionRequest: typing_extensions.TypeAlias = InvalidateSessionRequest

@typing.final
class InvalidateSessionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    success: builtins.bool
    message: builtins.str
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "success", b"success"]) -> None: ...

Global___InvalidateSessionResponse: typing_extensions.TypeAlias = InvalidateSessionResponse
