# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telegram.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telegram.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etelegram.proto\x12\x04\x61uth\">\n\x13StoreSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x16\n\x0esession_string\x18\x02 \x01(\t\"\x16\n\x14StoreSessionResponse\"?\n\x11GetSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x19\n\x11include_encrypted\x18\x02 \x01(\x08\"o\n\x12GetSessionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0esession_string\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\x12\x0e\n\x06\x65xists\x18\x04 \x01(\x08\x12\x0f\n\x07message\x18\x05 \x01(\t\";\n\x18InvalidateSessionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"=\n\x19InvalidateSessionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xef\x01\n\x0fTelegramService\x12\x45\n\x0cStoreSession\x12\x19.auth.StoreSessionRequest\x1a\x1a.auth.StoreSessionResponse\x12?\n\nGetSession\x12\x17.auth.GetSessionRequest\x1a\x18.auth.GetSessionResponse\x12T\n\x11InvalidateSession\x12\x1e.auth.InvalidateSessionRequest\x1a\x1f.auth.InvalidateSessionResponseB#\xaa\x02 Personage.Auth.Api.Grpc.Telegramb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telegram_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002 Personage.Auth.Api.Grpc.Telegram'
  _globals['_STORESESSIONREQUEST']._serialized_start=24
  _globals['_STORESESSIONREQUEST']._serialized_end=86
  _globals['_STORESESSIONRESPONSE']._serialized_start=88
  _globals['_STORESESSIONRESPONSE']._serialized_end=110
  _globals['_GETSESSIONREQUEST']._serialized_start=112
  _globals['_GETSESSIONREQUEST']._serialized_end=175
  _globals['_GETSESSIONRESPONSE']._serialized_start=177
  _globals['_GETSESSIONRESPONSE']._serialized_end=288
  _globals['_INVALIDATESESSIONREQUEST']._serialized_start=290
  _globals['_INVALIDATESESSIONREQUEST']._serialized_end=349
  _globals['_INVALIDATESESSIONRESPONSE']._serialized_start=351
  _globals['_INVALIDATESESSIONRESPONSE']._serialized_end=412
  _globals['_TELEGRAMSERVICE']._serialized_start=415
  _globals['_TELEGRAMSERVICE']._serialized_end=654
# @@protoc_insertion_point(module_scope)
