"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetUserChatsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_STRING_FIELD_NUMBER: builtins.int
    session_string: builtins.str
    def __init__(
        self,
        *,
        session_string: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["session_string", b"session_string"]) -> None: ...

Global___GetUserChatsRequest: typing_extensions.TypeAlias = GetUserChatsRequest

@typing.final
class GetUserChatsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Chat(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        id: builtins.int
        name: builtins.str
        def __init__(
            self,
            *,
            id: builtins.int = ...,
            name: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["id", b"id", "name", b"name"]) -> None: ...

    CHATS_FIELD_NUMBER: builtins.int
    @property
    def chats(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___GetUserChatsResponse.Chat]: ...
    def __init__(
        self,
        *,
        chats: collections.abc.Iterable[Global___GetUserChatsResponse.Chat] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["chats", b"chats"]) -> None: ...

Global___GetUserChatsResponse: typing_extensions.TypeAlias = GetUserChatsResponse
