grpc:
  port: 8080

http:
  port: 9090

swagger-ui:
  enabled: true

logging:
  level: debug
  format: console

sqs:
  endpoint: https://message-queue.api.cloud.yandex.net
  region: ru-central1
  accessKey: "secret:e6q869h32umj7dap12qa:e6q1l84sfb3f05qqu03e:access_key_id"
  secretKey: "secret:e6q869h32umj7dap12qa:e6q1l84sfb3f05qqu03e:secret_key"
  queueUrl: https://message-queue.api.cloud.yandex.net/b1gfkhf234165rrluh60/dj60000000bu18uu03cs/connector-events.fifo

database:
  host: localhost
  port: 5432
  user: user
  password: pass
  database: tasker
  options: sslmode=disable

llm:
  model: nvidia/nemotron-3-super-120b-a12b:free
  apiKey: "secret:e6qd2ljggdrvefjgg0gf:e6q72jfficuq9om25sab:open-router"

embedding:
  model: openai/text-embedding-3-small
  apiKey: "secret:e6qd2ljggdrvefjgg0gf:e6q72jfficuq9om25sab:open-router"

scheduling:
  windowHours: 24
  interval: 30s

notifications:
  upcomingEventMinPriority: 5
  upcomingEventIntervals:
    - 60m
    - 15m
    - 5m
  scheduleChangesEnabled: true

notifications-worker:
  interval: 1m

sqs-notificator:
  endpoint: https://message-queue.api.cloud.yandex.net
  region: ru-central1
  accessKey: "secret:e6q869h32umj7dap12qa:e6q1l84sfb3f05qqu03e:access_key_id"
  secretKey: "secret:e6q869h32umj7dap12qa:e6q1l84sfb3f05qqu03e:secret_key"
  queueUrl: https://message-queue.api.cloud.yandex.net/b1gfkhf234165rrluh60/dj60000000gqu7d103cs/notificator-commands

auth:
  address: grpc-auth.persomanage.ru:443