syntax = "proto3";

package auth;

option go_package = "github.com/Doremi203/personage/backend/libs/go/auth/gen/api/auth";

import "api/auth/common.proto";
import "google/protobuf/timestamp.proto";

service AuthService {
  rpc GetGmailTokens(GetGmailTokensRequest) returns (GmailTokens) {}
  rpc VerifyToken(VerifyTokenRequest) returns (VerifyTokenResponse) {}
  rpc GetUserProfile(GetUserProfileRequest) returns (UserProfile) {}
}

message GetGmailTokensRequest {
  string user_email = 1;
}

message VerifyTokenRequest {
  string token = 1;
}

message VerifyTokenResponse {
  bool is_valid = 1;
}

message GetUserProfileRequest {
  string user_id = 1;
}

message UserProfile {
  string user_id = 1;
  string email = 2;
  string name = 3;
  google.protobuf.Timestamp created_at = 4;
  repeated string connected_emails = 5;
}
