"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetInternalProcessingInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetInternalProcessingInfoRequest: typing_extensions.TypeAlias = GetInternalProcessingInfoRequest

@typing.final
class GetInternalProcessingInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INFOS_FIELD_NUMBER: builtins.int
    @property
    def infos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___InternalProcessingInfo]: ...
    def __init__(
        self,
        *,
        infos: collections.abc.Iterable[Global___InternalProcessingInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["infos", b"infos"]) -> None: ...

Global___GetInternalProcessingInfoResponse: typing_extensions.TypeAlias = GetInternalProcessingInfoResponse

@typing.final
class InternalProcessingInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    GMAIL_COUNTER_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    gmail_counter: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        gmail_counter: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_gmail_counter", b"_gmail_counter", "gmail_counter", b"gmail_counter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_gmail_counter", b"_gmail_counter", "gmail_counter", b"gmail_counter", "user_id", b"user_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_gmail_counter", b"_gmail_counter"]) -> typing.Literal["gmail_counter"] | None: ...

Global___InternalProcessingInfo: typing_extensions.TypeAlias = InternalProcessingInfo

@typing.final
class RollbackGmailProcessingRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    DECREASE_PROCESSING_COUNTER_BY_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    decrease_processing_counter_by: builtins.int
    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        decrease_processing_counter_by: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["decrease_processing_counter_by", b"decrease_processing_counter_by", "user_id", b"user_id"]) -> None: ...

Global___RollbackGmailProcessingRequest: typing_extensions.TypeAlias = RollbackGmailProcessingRequest

@typing.final
class RollbackGmailProcessingResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPDATED_PROCESSING_COUNTER_FIELD_NUMBER: builtins.int
    updated_processing_counter: builtins.int
    def __init__(
        self,
        *,
        updated_processing_counter: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_updated_processing_counter", b"_updated_processing_counter", "updated_processing_counter", b"updated_processing_counter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_updated_processing_counter", b"_updated_processing_counter", "updated_processing_counter", b"updated_processing_counter"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_updated_processing_counter", b"_updated_processing_counter"]) -> typing.Literal["updated_processing_counter"] | None: ...

Global___RollbackGmailProcessingResponse: typing_extensions.TypeAlias = RollbackGmailProcessingResponse
