# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import debug_pb2 as debug__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in debug_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DebugServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RollbackGmailProcessing = channel.unary_unary(
                '/api.debug.DebugService/RollbackGmailProcessing',
                request_serializer=debug__pb2.RollbackGmailProcessingRequest.SerializeToString,
                response_deserializer=debug__pb2.RollbackGmailProcessingResponse.FromString,
                _registered_method=True)
        self.GetInternalProcessingInfo = channel.unary_unary(
                '/api.debug.DebugService/GetInternalProcessingInfo',
                request_serializer=debug__pb2.GetInternalProcessingInfoRequest.SerializeToString,
                response_deserializer=debug__pb2.GetInternalProcessingInfoResponse.FromString,
                _registered_method=True)


class DebugServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RollbackGmailProcessing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInternalProcessingInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DebugServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RollbackGmailProcessing': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackGmailProcessing,
                    request_deserializer=debug__pb2.RollbackGmailProcessingRequest.FromString,
                    response_serializer=debug__pb2.RollbackGmailProcessingResponse.SerializeToString,
            ),
            'GetInternalProcessingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInternalProcessingInfo,
                    request_deserializer=debug__pb2.GetInternalProcessingInfoRequest.FromString,
                    response_serializer=debug__pb2.GetInternalProcessingInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.debug.DebugService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.debug.DebugService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DebugService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RollbackGmailProcessing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.debug.DebugService/RollbackGmailProcessing',
            debug__pb2.RollbackGmailProcessingRequest.SerializeToString,
            debug__pb2.RollbackGmailProcessingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInternalProcessingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.debug.DebugService/GetInternalProcessingInfo',
            debug__pb2.GetInternalProcessingInfoRequest.SerializeToString,
            debug__pb2.GetInternalProcessingInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
