# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: debug.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'debug.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x65\x62ug.proto\x12\tapi.debug\x1a\x1fgoogle/protobuf/timestamp.proto\"\"\n GetInternalProcessingInfoRequest\"U\n!GetInternalProcessingInfoResponse\x12\x30\n\x05infos\x18\x01 \x03(\x0b\x32!.api.debug.InternalProcessingInfo\"W\n\x16InternalProcessingInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1a\n\rgmail_counter\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x10\n\x0e_gmail_counter\"Y\n\x1eRollbackGmailProcessingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12&\n\x1e\x64\x65\x63rease_processing_counter_by\x18\x02 \x01(\x05\"i\n\x1fRollbackGmailProcessingResponse\x12\'\n\x1aupdated_processing_counter\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x1d\n\x1b_updated_processing_counter2\xfc\x01\n\x0c\x44\x65\x62ugService\x12r\n\x17RollbackGmailProcessing\x12).api.debug.RollbackGmailProcessingRequest\x1a*.api.debug.RollbackGmailProcessingResponse\"\x00\x12x\n\x19GetInternalProcessingInfo\x12+.api.debug.GetInternalProcessingInfoRequest\x1a,.api.debug.GetInternalProcessingInfoResponse\"\x00\x42>Z<github.com/amoguscorp/personage/backend/tasker/gen/api/debugb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'debug_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/amoguscorp/personage/backend/tasker/gen/api/debug'
  _globals['_GETINTERNALPROCESSINGINFOREQUEST']._serialized_start=59
  _globals['_GETINTERNALPROCESSINGINFOREQUEST']._serialized_end=93
  _globals['_GETINTERNALPROCESSINGINFORESPONSE']._serialized_start=95
  _globals['_GETINTERNALPROCESSINGINFORESPONSE']._serialized_end=180
  _globals['_INTERNALPROCESSINGINFO']._serialized_start=182
  _globals['_INTERNALPROCESSINGINFO']._serialized_end=269
  _globals['_ROLLBACKGMAILPROCESSINGREQUEST']._serialized_start=271
  _globals['_ROLLBACKGMAILPROCESSINGREQUEST']._serialized_end=360
  _globals['_ROLLBACKGMAILPROCESSINGRESPONSE']._serialized_start=362
  _globals['_ROLLBACKGMAILPROCESSINGRESPONSE']._serialized_end=467
  _globals['_DEBUGSERVICE']._serialized_start=470
  _globals['_DEBUGSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
