"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ConnectorType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ConnectorTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ConnectorType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    CONNECTOR_TYPE_UNKNOWN: _ConnectorType.ValueType  # 0
    CONNECTOR_TYPE_GMAIL: _ConnectorType.ValueType  # 1
    CONNECTOR_TYPE_TELEGRAM: _ConnectorType.ValueType  # 2
    CONNECTOR_TYPE_GOOGLE_CALENDAR: _ConnectorType.ValueType  # 3

class ConnectorType(_ConnectorType, metaclass=_ConnectorTypeEnumTypeWrapper): ...

CONNECTOR_TYPE_UNKNOWN: ConnectorType.ValueType  # 0
CONNECTOR_TYPE_GMAIL: ConnectorType.ValueType  # 1
CONNECTOR_TYPE_TELEGRAM: ConnectorType.ValueType  # 2
CONNECTOR_TYPE_GOOGLE_CALENDAR: ConnectorType.ValueType  # 3
Global___ConnectorType: typing_extensions.TypeAlias = ConnectorType

@typing.final
class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    CONNECTOR_TYPE_FIELD_NUMBER: builtins.int
    OCCURRED_AT_FIELD_NUMBER: builtins.int
    CONTEXT_FIELD_NUMBER: builtins.int
    id: builtins.str
    user_id: builtins.str
    connector_type: Global___ConnectorType.ValueType
    @property
    def occurred_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def context(self) -> Global___Context: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        user_id: builtins.str = ...,
        connector_type: Global___ConnectorType.ValueType = ...,
        occurred_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        context: Global___Context | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["context", b"context", "occurred_at", b"occurred_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["connector_type", b"connector_type", "context", b"context", "id", b"id", "occurred_at", b"occurred_at", "user_id", b"user_id"]) -> None: ...

Global___Event: typing_extensions.TypeAlias = Event

@typing.final
class Context(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Subject(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        name: builtins.str
        def __init__(
            self,
            *,
            name: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

    @typing.final
    class Location(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ADDRESS_FIELD_NUMBER: builtins.int
        address: builtins.str
        def __init__(
            self,
            *,
            address: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["address", b"address"]) -> None: ...

    @typing.final
    class Attachment(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        name: builtins.str
        def __init__(
            self,
            *,
            name: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

    @typing.final
    class Participant(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NAME_FIELD_NUMBER: builtins.int
        TELEGRAM_USER_FIELD_NUMBER: builtins.int
        EMAIL_FIELD_NUMBER: builtins.int
        name: builtins.str
        email: builtins.str
        @property
        def telegram_user(self) -> Global___TelegramUser: ...
        def __init__(
            self,
            *,
            name: builtins.str | None = ...,
            telegram_user: Global___TelegramUser | None = ...,
            email: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_email", b"_email", "_name", b"_name", "_telegram_user", b"_telegram_user", "email", b"email", "name", b"name", "telegram_user", b"telegram_user"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_email", b"_email", "_name", b"_name", "_telegram_user", b"_telegram_user", "email", b"email", "name", b"name", "telegram_user", b"telegram_user"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_email", b"_email"]) -> typing.Literal["email"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_telegram_user", b"_telegram_user"]) -> typing.Literal["telegram_user"] | None: ...

    BODY_FIELD_NUMBER: builtins.int
    SUBJECT_FIELD_NUMBER: builtins.int
    TIME_FRAME_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    ATTACHMENTS_FIELD_NUMBER: builtins.int
    OTHER_PARTICIPANTS_FIELD_NUMBER: builtins.int
    SENDER_FIELD_NUMBER: builtins.int
    body: builtins.str
    @property
    def subject(self) -> Global___Context.Subject: ...
    @property
    def time_frame(self) -> Global___TimeFrame: ...
    @property
    def location(self) -> Global___Context.Location: ...
    @property
    def attachments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Context.Attachment]: ...
    @property
    def other_participants(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___Context.Participant]: ...
    @property
    def sender(self) -> Global___Context.Participant: ...
    def __init__(
        self,
        *,
        body: builtins.str = ...,
        subject: Global___Context.Subject | None = ...,
        time_frame: Global___TimeFrame | None = ...,
        location: Global___Context.Location | None = ...,
        attachments: collections.abc.Iterable[Global___Context.Attachment] | None = ...,
        other_participants: collections.abc.Iterable[Global___Context.Participant] | None = ...,
        sender: Global___Context.Participant | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_location", b"_location", "_sender", b"_sender", "_subject", b"_subject", "_time_frame", b"_time_frame", "location", b"location", "sender", b"sender", "subject", b"subject", "time_frame", b"time_frame"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_location", b"_location", "_sender", b"_sender", "_subject", b"_subject", "_time_frame", b"_time_frame", "attachments", b"attachments", "body", b"body", "location", b"location", "other_participants", b"other_participants", "sender", b"sender", "subject", b"subject", "time_frame", b"time_frame"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_location", b"_location"]) -> typing.Literal["location"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_sender", b"_sender"]) -> typing.Literal["sender"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_subject", b"_subject"]) -> typing.Literal["subject"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_time_frame", b"_time_frame"]) -> typing.Literal["time_frame"] | None: ...

Global___Context: typing_extensions.TypeAlias = Context

@typing.final
class TimeFrame(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    START_FIELD_NUMBER: builtins.int
    END_FIELD_NUMBER: builtins.int
    @property
    def start(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def end(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        start: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        end: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["end", b"end", "start", b"start"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["end", b"end", "start", b"start"]) -> None: ...

Global___TimeFrame: typing_extensions.TypeAlias = TimeFrame

@typing.final
class TelegramUser(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    tag: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        tag: builtins.str | None = ...,
        name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_name", b"_name", "_tag", b"_tag", "name", b"name", "tag", b"tag"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_name", b"_name", "_tag", b"_tag", "id", b"id", "name", b"name", "tag", b"tag"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_name", b"_name"]) -> typing.Literal["name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tag", b"_tag"]) -> typing.Literal["tag"] | None: ...

Global___TelegramUser: typing_extensions.TypeAlias = TelegramUser
