"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ProcessingSnapshot(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FROM__FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int
    id: builtins.str
    @property
    def from_(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def to(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        from_: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        to: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["from_", b"from_", "to", b"to"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["from_", b"from_", "id", b"id", "to", b"to"]) -> None: ...

Global___ProcessingSnapshot: typing_extensions.TypeAlias = ProcessingSnapshot

@typing.final
class GetProcessingSnapshotsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetProcessingSnapshotsRequest: typing_extensions.TypeAlias = GetProcessingSnapshotsRequest

@typing.final
class GetProcessingSnapshotsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SNAPSHOTS_FIELD_NUMBER: builtins.int
    @property
    def snapshots(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[Global___ProcessingSnapshot]: ...
    def __init__(
        self,
        *,
        snapshots: collections.abc.Iterable[Global___ProcessingSnapshot] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["snapshots", b"snapshots"]) -> None: ...

Global___GetProcessingSnapshotsResponse: typing_extensions.TypeAlias = GetProcessingSnapshotsResponse

@typing.final
class CreateProcessingSnapshotRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM__FIELD_NUMBER: builtins.int
    TO_FIELD_NUMBER: builtins.int
    @property
    def from_(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def to(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        from_: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        to: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["from_", b"from_", "to", b"to"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["from_", b"from_", "to", b"to"]) -> None: ...

Global___CreateProcessingSnapshotRequest: typing_extensions.TypeAlias = CreateProcessingSnapshotRequest

@typing.final
class CreateProcessingSnapshotResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SNAPSHOT_ID_FIELD_NUMBER: builtins.int
    snapshot_id: builtins.str
    def __init__(
        self,
        *,
        snapshot_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["snapshot_id", b"snapshot_id"]) -> None: ...

Global___CreateProcessingSnapshotResponse: typing_extensions.TypeAlias = CreateProcessingSnapshotResponse

@typing.final
class CreateSnapshotFromCurrentMomentRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOR_SECONDS_FIELD_NUMBER: builtins.int
    for_seconds: builtins.int
    def __init__(
        self,
        *,
        for_seconds: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["for_seconds", b"for_seconds"]) -> None: ...

Global___CreateSnapshotFromCurrentMomentRequest: typing_extensions.TypeAlias = CreateSnapshotFromCurrentMomentRequest

@typing.final
class CreateSnapshotFromCurrentMomentResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SNAPSHOT_ID_FIELD_NUMBER: builtins.int
    snapshot_id: builtins.str
    def __init__(
        self,
        *,
        snapshot_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["snapshot_id", b"snapshot_id"]) -> None: ...

Global___CreateSnapshotFromCurrentMomentResponse: typing_extensions.TypeAlias = CreateSnapshotFromCurrentMomentResponse

@typing.final
class SendProcessingSnapshotRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SNAPSHOT_ID_FIELD_NUMBER: builtins.int
    snapshot_id: builtins.str
    def __init__(
        self,
        *,
        snapshot_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["snapshot_id", b"snapshot_id"]) -> None: ...

Global___SendProcessingSnapshotRequest: typing_extensions.TypeAlias = SendProcessingSnapshotRequest

@typing.final
class SendProcessingSnapshotResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENTS_COUNT_FIELD_NUMBER: builtins.int
    events_count: builtins.int
    def __init__(
        self,
        *,
        events_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["events_count", b"events_count"]) -> None: ...

Global___SendProcessingSnapshotResponse: typing_extensions.TypeAlias = SendProcessingSnapshotResponse
