# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: processing.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'processing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10processing.proto\x12\x0e\x61pi.processing\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\x12ProcessingSnapshot\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x05\x66rom_\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1f\n\x1dGetProcessingSnapshotsRequest\"W\n\x1eGetProcessingSnapshotsResponse\x12\x35\n\tsnapshots\x18\x01 \x03(\x0b\x32\".api.processing.ProcessingSnapshot\"t\n\x1f\x43reateProcessingSnapshotRequest\x12)\n\x05\x66rom_\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"7\n CreateProcessingSnapshotResponse\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\"=\n&CreateSnapshotFromCurrentMomentRequest\x12\x13\n\x0b\x66or_seconds\x18\x01 \x01(\x05\">\n\'CreateSnapshotFromCurrentMomentResponse\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\"h\n\x1dSendProcessingSnapshotRequest\x12\x13\n\x0bsnapshot_id\x18\x01 \x01(\t\x12\x1d\n\x10target_queue_url\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x13\n\x11_target_queue_url\"6\n\x1eSendProcessingSnapshotResponse\x12\x14\n\x0c\x65vents_count\x18\x01 \x01(\x05\x32\xa1\x04\n\x11ProcessingService\x12y\n\x16SendProcessingSnapshot\x12-.api.processing.SendProcessingSnapshotRequest\x1a..api.processing.SendProcessingSnapshotResponse\"\x00\x12y\n\x16GetProcessingSnapshots\x12-.api.processing.GetProcessingSnapshotsRequest\x1a..api.processing.GetProcessingSnapshotsResponse\"\x00\x12\x7f\n\x18\x43reateProcessingSnapshot\x12/.api.processing.CreateProcessingSnapshotRequest\x1a\x30.api.processing.CreateProcessingSnapshotResponse\"\x00\x12\x94\x01\n\x1f\x43reateSnapshotFromCurrentMoment\x12\x36.api.processing.CreateSnapshotFromCurrentMomentRequest\x1a\x37.api.processing.CreateSnapshotFromCurrentMomentResponse\"\x00\x42\x43ZAgithub.com/amoguscorp/personage/backend/tasker/gen/api/processingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/amoguscorp/personage/backend/tasker/gen/api/processing'
  _globals['_PROCESSINGSNAPSHOT']._serialized_start=69
  _globals['_PROCESSINGSNAPSHOT']._serialized_end=184
  _globals['_GETPROCESSINGSNAPSHOTSREQUEST']._serialized_start=186
  _globals['_GETPROCESSINGSNAPSHOTSREQUEST']._serialized_end=217
  _globals['_GETPROCESSINGSNAPSHOTSRESPONSE']._serialized_start=219
  _globals['_GETPROCESSINGSNAPSHOTSRESPONSE']._serialized_end=306
  _globals['_CREATEPROCESSINGSNAPSHOTREQUEST']._serialized_start=308
  _globals['_CREATEPROCESSINGSNAPSHOTREQUEST']._serialized_end=424
  _globals['_CREATEPROCESSINGSNAPSHOTRESPONSE']._serialized_start=426
  _globals['_CREATEPROCESSINGSNAPSHOTRESPONSE']._serialized_end=481
  _globals['_CREATESNAPSHOTFROMCURRENTMOMENTREQUEST']._serialized_start=483
  _globals['_CREATESNAPSHOTFROMCURRENTMOMENTREQUEST']._serialized_end=544
  _globals['_CREATESNAPSHOTFROMCURRENTMOMENTRESPONSE']._serialized_start=546
  _globals['_CREATESNAPSHOTFROMCURRENTMOMENTRESPONSE']._serialized_end=608
  _globals['_SENDPROCESSINGSNAPSHOTREQUEST']._serialized_start=610
  _globals['_SENDPROCESSINGSNAPSHOTREQUEST']._serialized_end=714
  _globals['_SENDPROCESSINGSNAPSHOTRESPONSE']._serialized_start=716
  _globals['_SENDPROCESSINGSNAPSHOTRESPONSE']._serialized_end=770
  _globals['_PROCESSINGSERVICE']._serialized_start=773
  _globals['_PROCESSINGSERVICE']._serialized_end=1318
# @@protoc_insertion_point(module_scope)
