# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import processing_pb2 as processing__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in processing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProcessingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendProcessingSnapshot = channel.unary_unary(
                '/api.processing.ProcessingService/SendProcessingSnapshot',
                request_serializer=processing__pb2.SendProcessingSnapshotRequest.SerializeToString,
                response_deserializer=processing__pb2.SendProcessingSnapshotResponse.FromString,
                _registered_method=True)
        self.GetProcessingSnapshots = channel.unary_unary(
                '/api.processing.ProcessingService/GetProcessingSnapshots',
                request_serializer=processing__pb2.GetProcessingSnapshotsRequest.SerializeToString,
                response_deserializer=processing__pb2.GetProcessingSnapshotsResponse.FromString,
                _registered_method=True)
        self.CreateProcessingSnapshot = channel.unary_unary(
                '/api.processing.ProcessingService/CreateProcessingSnapshot',
                request_serializer=processing__pb2.CreateProcessingSnapshotRequest.SerializeToString,
                response_deserializer=processing__pb2.CreateProcessingSnapshotResponse.FromString,
                _registered_method=True)
        self.CreateSnapshotFromCurrentMoment = channel.unary_unary(
                '/api.processing.ProcessingService/CreateSnapshotFromCurrentMoment',
                request_serializer=processing__pb2.CreateSnapshotFromCurrentMomentRequest.SerializeToString,
                response_deserializer=processing__pb2.CreateSnapshotFromCurrentMomentResponse.FromString,
                _registered_method=True)


class ProcessingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendProcessingSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessingSnapshots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProcessingSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSnapshotFromCurrentMoment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendProcessingSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.SendProcessingSnapshot,
                    request_deserializer=processing__pb2.SendProcessingSnapshotRequest.FromString,
                    response_serializer=processing__pb2.SendProcessingSnapshotResponse.SerializeToString,
            ),
            'GetProcessingSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessingSnapshots,
                    request_deserializer=processing__pb2.GetProcessingSnapshotsRequest.FromString,
                    response_serializer=processing__pb2.GetProcessingSnapshotsResponse.SerializeToString,
            ),
            'CreateProcessingSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProcessingSnapshot,
                    request_deserializer=processing__pb2.CreateProcessingSnapshotRequest.FromString,
                    response_serializer=processing__pb2.CreateProcessingSnapshotResponse.SerializeToString,
            ),
            'CreateSnapshotFromCurrentMoment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSnapshotFromCurrentMoment,
                    request_deserializer=processing__pb2.CreateSnapshotFromCurrentMomentRequest.FromString,
                    response_serializer=processing__pb2.CreateSnapshotFromCurrentMomentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.processing.ProcessingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.processing.ProcessingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProcessingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendProcessingSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.processing.ProcessingService/SendProcessingSnapshot',
            processing__pb2.SendProcessingSnapshotRequest.SerializeToString,
            processing__pb2.SendProcessingSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcessingSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.processing.ProcessingService/GetProcessingSnapshots',
            processing__pb2.GetProcessingSnapshotsRequest.SerializeToString,
            processing__pb2.GetProcessingSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProcessingSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.processing.ProcessingService/CreateProcessingSnapshot',
            processing__pb2.CreateProcessingSnapshotRequest.SerializeToString,
            processing__pb2.CreateProcessingSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSnapshotFromCurrentMoment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.processing.ProcessingService/CreateSnapshotFromCurrentMoment',
            processing__pb2.CreateSnapshotFromCurrentMomentRequest.SerializeToString,
            processing__pb2.CreateSnapshotFromCurrentMomentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
