name: Tasker Service Release Flow
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    uses: ./.github/workflows/go-service-release.yml
    with:
      service_name: tasker
      db_name: tasker
      run_functional_tests: 'true'
    secrets: inherit